os: linux
dist: bionic
install: true

addons:
  apt:
    packages:
    - git

services:
  - mongodb
  - docker


language: python

python:
  - "3.7"

script:
  - bash ./run-build-and-tests.sh

deploy:
  - provider: script
    script: bash docker_push
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bash docker_push
    skip_cleanup: true
    on:
      branch: ZhHans
