name: build
on:
    push:
        branches:
            - main
            - master
            - with_cjk_font

jobs:
    build:
        name: Build docker images
        runs-on: ubuntu-latest
        env:
            MY_EXTRA_FONTS_GZ: ${{ secrets.MY_EXTRA_FONTS_GZ }}
            EXTRA_PACKAGE: ${{ secrets.EXTRA_PACKAGE }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            COMMIT_SHA: ${{ github.sha }}
        steps:
            - uses: actions/checkout@v1
            - uses: EthanSK/git-branch-name-action@v1
            - name: Build docker image
              env:
                  BRANCH_NAME: ${{ env.GIT_BRANCH_NAME }}
              run: bash ./run-build-and-tests.sh
            - name: Upload docker image
              env:
                  BRANCH_NAME: ${{ env.GIT_BRANCH_NAME }}
              run: bash ./docker_push
